[package]
name = "penguin"
version = "0.1.2"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
bitflags = "2.6.0"
byteorder = "1.5.0"
crc32fast = "1.4.2"
eframe = "0.30.0"
egui = "0.30.0"
image = "0.25.5"
json = "0.12.4"
rfd = "0.15.0"
